### ISSUE TITLE
Can only run one of these in a given Go app

### ISSUE THREAD

**Issue by lordmortis** [h2ik/go-sqs-poller#1]
Because of the way QueueURL is defined, you can only run one of these polls in a given application/exectuable.

I've done some modifications in [my fork](https://github.com/h2ik/go-sqs-poller/compare/master...StirfireStudios:master) - if these are acceptable to you, i can clean up the example and do a Pull Request.

**Comment by jwhitcraft** [comment]
Sure do a pull request.

**Comment by jwhitcraft** [comment]
This is now fixed.
